import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "../globals.css";
import { Pages } from "../../../sanity/sanity-utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Portfolio Site",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Get all of our pages
  const pages = await Pages();
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-4xl mx-auto py-10`}>
        <header className="flex items-center justify-between">
          <Link
            href={"/"}
            className="mt-2 bg-gradient-to-r from-orange-400 to
              bg-purple-600 via-red-500 bg-clip-text text-transparent text-lg font-bold drop-shadow-2xl"
          >
            Home
          </Link>
          <div className="flex items-center gap-5 text-md   text-gray-600">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-10">{children}</main>
      </body>
    </html>
  );
}
